<<<<<<< Updated upstream
// ---------------------------------------------
// sky_clouds.c - Procedural cloud system
// ---------------------------------------------

=======
/*
 * Original cloud implementation was too random and didn't achieve the expected shape.
 * Used Claude to implement clouds based on the Real-Time Rendering billboards chapter.
 * Pretty much main components of this file are generated by AI.
 */
 
#include "CSCIx229.h"
>>>>>>> Stashed changes
#include "sky_clouds.h"
#include <stdlib.h>
#include <math.h>
#include "landscape.h"

<<<<<<< Updated upstream
#ifdef __APPLE__
#include <GLUT/glut.h>
#include <OpenGL/gl.h>
#else
#include <GL/glut.h>
#include <GL/gl.h>
#endif

// --- Cloud system creation ---
/* Creates a cloud system with random formations */
SkyCloudSystem* skyCloudSystemCreate(float baseHeight) {
    SkyCloudSystem* cs = (SkyCloudSystem*)malloc(sizeof(SkyCloudSystem));
    if (!cs) return NULL;
    cs->cloudCount = 120;
    cs->baseHeight = baseHeight;
    cs->windSpeed = 0.15f;
    for (int i = 0; i < cs->cloudCount; i++) {
        SkyCloud* cloud = &cs->clouds[i];
        cloud->x = ((float)rand()/RAND_MAX - 0.5f) * LANDSCAPE_SCALE * 1.2f;
        cloud->z = ((float)rand()/RAND_MAX - 0.5f) * LANDSCAPE_SCALE * 1.2f;
        cloud->y = baseHeight + 60.0f + ((float)rand()/RAND_MAX) * 10.0f;
        cloud->size = 20.0f + ((float)rand()/RAND_MAX) * 15.0f;
        cloud->alpha = 0.3f + ((float)rand()/RAND_MAX) * 0.2f;
        cloud->speed = 0.05f + ((float)rand()/RAND_MAX) * 0.05f;
        cloud->variation = ((float)rand()/RAND_MAX);
    }
    return cs;
}

// --- Cloud update logic ---
/* Updates cloud positions and recycles clouds outside bounds */
void skyCloudSystemUpdate(SkyCloudSystem* cs, float deltaTime, float dayTime) {
    for (int i = 0; i < cs->cloudCount; i++) {
        SkyCloud* cloud = &cs->clouds[i];
        cloud->x += cloud->speed * cs->windSpeed * deltaTime;
        if (cloud->x > LANDSCAPE_SCALE) {
            cloud->x = -LANDSCAPE_SCALE;
            cloud->z = ((float)rand()/RAND_MAX - 0.5f) * LANDSCAPE_SCALE;
            cloud->size = 30.0f + ((float)rand()/RAND_MAX) * 20.0f;
            cloud->alpha = 0.15f + ((float)rand()/RAND_MAX) * 0.15f;
        }
=======
static void setAtmosphericCloudProperties(AtmosphericCloud* cloud, float baseAltitude) {
    cloud->posX = ((float)rand() / RAND_MAX - 0.5f) * LANDSCAPE_SCALE * 1.7f;
    cloud->posZ = ((float)rand() / RAND_MAX - 0.5f) * LANDSCAPE_SCALE * 1.7f;
    cloud->posY = baseAltitude + 48.0f + ((float)rand() / RAND_MAX) * 22.0f;
    cloud->radius = 24.0f + ((float)rand() / RAND_MAX) * 13.0f;
    cloud->opacity = 0.28f + ((float)rand() / RAND_MAX) * 0.23f;
}

AtmosphericCloudSystem* atmosphericCloudSystemCreate(float referenceAltitude) {
    AtmosphericCloudSystem* system = (AtmosphericCloudSystem*)malloc(sizeof(AtmosphericCloudSystem));
    if (!system) return NULL;
    system->numClouds = 88;
    system->baseAltitude = referenceAltitude + 42.0f;
    for (int idx = 0; idx < system->numClouds; idx++) {
        setAtmosphericCloudProperties(&system->cloudBank[idx], system->baseAltitude);
    }
    return system;
}

// Claude generated this function, based on inputs I gave from the realtime rendering book, Billboarding chapter
static void renderAtmosphericCloudLayer(const AtmosphericCloud* cloud, int stratum) {
    float t = (float)stratum / 5.0f;
    float bulge = sinf(t * M_PI) * 1.6f;
    float stratumRadius = cloud->radius * (1.0f - t * 0.22f);
    float stratumOpacity = cloud->opacity * (0.58f - t * 0.11f);
    float stratumAltitude = cloud->posY + bulge * 13.0f;
    
    glBegin(GL_TRIANGLE_FAN);
    glColor4f(1.0f, 1.0f, 1.0f, stratumOpacity);
    glVertex3f(cloud->posX, stratumAltitude + bulge * 2.7f, cloud->posZ);
    
    for (int j = 0; j <= 18; j++) {
        float angle = (float)j / 18 * 2 * M_PI;
        float radialDist = 0.83f + 0.17f * sinf(angle * 2 + cloud->posX * 0.13f);
        float variation = 1.0f + 0.19f * cosf(angle * 3 + cloud->posZ * 0.13f);
        float px = cloud->posX + cosf(angle) * stratumRadius * variation * radialDist;
        float pz = cloud->posZ + sinf(angle) * stratumRadius * variation * radialDist;
        float py = stratumAltitude + bulge * (1.0f - radialDist) * 7.0f + sinf(angle * 2) * bulge * 2.7f;
        glVertex3f(px, py, pz);
>>>>>>> Stashed changes
    }
    glEnd();
}

<<<<<<< Updated upstream
// --- Cloud rendering ---
/* Renders clouds as multi-layered billboards */
void skyCloudSystemRender(SkyCloudSystem* cs, float dayTime) {
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glDisable(GL_LIGHTING);
    glDisable(GL_DEPTH_TEST);
    float timeNormalized = dayTime / 24.0f;
    float sunHeight = sin((timeNormalized - 0.25f) * 2 * M_PI);
    float brightness = 0.95f + 0.05f * fmaxf(sunHeight, 0.0f);
    for (int i = 0; i < cs->cloudCount; i++) {
        SkyCloud* cloud = &cs->clouds[i];
        for (int layer = 0; layer < 6; layer++) {
            float t = (float)layer / 5.0f;
            float bulge = sinf(t * M_PI) * 1.5f;
            float layerSize = cloud->size * (1.0f - t * 0.25f);
            float layerAlpha = cloud->alpha * (0.6f - t * 0.1f);
            float layerHeight = cloud->y + bulge * 12.0f;
            glBegin(GL_TRIANGLE_FAN);
            glColor4f(brightness, brightness, brightness, layerAlpha);
            glVertex3f(cloud->x, layerHeight + bulge * 3.0f, cloud->z);
            int segments = 16;
            for (int j = 0; j <= segments; j++) {
                float angle = (float)j / segments * 2 * M_PI;
                float radialDist = 0.85f + 0.15f * sinf(angle * 2 + cloud->x * 0.1f);
                float variation = 1.0f + 0.2f * cosf(angle * 3 + cloud->z * 0.1f);
                float px = cloud->x + cosf(angle) * layerSize * variation * radialDist;
                float pz = cloud->z + sinf(angle) * layerSize * variation * radialDist;
                float py = layerHeight + bulge * (1.0f - radialDist) * 6.0f + sinf(angle * 2) * bulge * 3.0f;
                glVertex3f(px, py, pz);
            }
            glEnd();
        }
=======
static void renderAtmosphericCloud(const AtmosphericCloud* cloud) {
    for (int stratum = 0; stratum < 6; stratum++) {
        renderAtmosphericCloudLayer(cloud, stratum);
    }
}
// claude generated code ends here

void atmosphericCloudSystemRender(AtmosphericCloudSystem* system) {
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glDisable(GL_LIGHTING);
    
    for (int idx = 0; idx < system->numClouds; idx++) {
        renderAtmosphericCloud(&system->cloudBank[idx]);
>>>>>>> Stashed changes
    }
    
    glEnable(GL_DEPTH_TEST);
    glEnable(GL_LIGHTING);
    glDisable(GL_BLEND);
}

<<<<<<< Updated upstream
// --- Cloud system cleanup ---
/* Frees cloud system memory */
void skyCloudSystemDestroy(SkyCloudSystem* cs) {
    if (cs) {
        free(cs);
=======
void atmosphericCloudSystemDestroy(AtmosphericCloudSystem* system) {
    if (system) {
        free(system);
>>>>>>> Stashed changes
    }
}